### ISSUE TITLE
Some clarifications

### ISSUE THREAD

**Issue by jasonfish568** [hyperjumptech/whatsapp-chatbot-connector#33]
Thanks so much for this amazing repo. I have successfully got my local environment up and running.

However, the below points should be able to help some fellow developers starting up:

1. `git clone https://github.com/yourusername/whatsapp-chatbot-connector.git` should be `git clone https://github.com/hyperjumptech/whatsapp-chatbot-connector.git`
2. `docker build -f Dockerfile` should be `docker build -t wa-connector` so it creates a image named as wa-connector and when your docker compose runs it finds the image
3. WhatsApp Business API Configuration: Callback URL must be using an SSL certificate which means it needs to start with https://

**Comment by raosan** [comment]
Hi @jasonfish568 , glad that you can use this repo successfully. And thanks for the feedback, i will update the readme.

**Comment by jasonfish568** [comment]
In addition:

1. Do you think this connector can support multiple whatsapp accounts?
2. I see a potential this connector can also handle Mailgun/Resend's webhook messages for handling Emails, what do you think?

**Comment by raosan** [comment]
AFAIK, it has 2 condition regarding multiple whatsapp account:
1. For receiving webhook. It **can** be used by many account as long as the webhook url is set the same
2. For sending reply. It **cannot** be used by many account because we need to pre set specific `BUSINESS_PHONE_NUMBER_ID` in the env.

As for mailgun/email, i think it should be done on another module and repo. "Single responsibility principle" wise
